import type { CanonSystem, CanonTopic } from './types';
import { fileKind } from './types';

/**
 * Canon → D1 seed generator. Turns a content module into an idempotent SQL
 * migration so canon and community posts share one store online (PRD: "canon
 * and community share one surface"). Topics key on (board, slug); posts key
 * on (topic, created_at) — re-running a seed inserts nothing. Seeded rows are
 * `canon=1 pinned=1` and immutable by construction: no API path updates or
 * deletes them. `pinned_rank` numbers topics in module order — the authored
 * fiction order the pinned block lists in, online and LOCAL MODE alike.
 *
 * The generated files are real migrations (migrations/dialer/000N_canon_*.sql),
 * locked to this generator by file-snapshot tests in seed.test.ts — editing a
 * content module without regenerating fails CI. Canon FILE areas seed the same
 * way (canonFilesSql): `canon=1` rows with deterministic ids, keyed on id, no
 * API write path touches them. Back Room files stay client-only — the Back
 * Room has no live layer.
 */

/**
 * Epoch seconds for a canon date, `MM/DD/YY` or `MM/DD/YY HH:MM` (UTC). The
 * two-digit year lives in the 1900s — this universe never sees Y2K. Undated
 * hours land at noon so date-only posts stay unambiguous.
 */
export function canonDateEpoch(date: string): number {
	const match = /^(\d{2})\/(\d{2})\/(\d{2})(?: (\d{2}):(\d{2}))?$/.exec(date);
	if (!match) throw new Error(`canon date doesn't scan: "${date}"`);
	const [, mm, dd, yy, hh, min] = match;
	return (
		Date.UTC(
			1900 + Number(yy),
			Number(mm) - 1,
			Number(dd),
			Number(hh ?? '12'),
			Number(min ?? '0')
		) / 1000
	);
}

/** The complete, idempotent seed SQL for one canon system's message boards. */
export function canonSeedSql(system: CanonSystem): string {
	const statements: string[] = [
		`-- Canon content seed: ${system.name} (${system.id}).`,
		`-- GENERATED by src/lib/apps/dialer/content/seed.ts from the ${system.id} content`,
		`-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with`,
		`--   pnpm test:unit -- --update`,
		`-- Idempotent: topics key on (board, slug), posts on (topic, created_at).`,
		''
	];
	let rank = 0;
	for (const section of system.sections) {
		for (const topic of section.topics) {
			statements.push(topicSql(system.id, section.slug, topic, rank++), '');
		}
	}
	return statements.join('\n');
}

function topicSql(board: string, section: string, topic: CanonTopic, rank: number): string {
	const createdAt = postEpoch(topic, 0);
	const lines = [
		`INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)`,
		`SELECT ${sql(board)}, ${sql(section)}, ${sql(topic.slug)}, ${sql(topic.title)}, ${sql(topic.posts[0].author)}, ${createdAt}, 1, 1, ${rank}`,
		`WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = ${sql(board)} AND slug = ${sql(topic.slug)});`
	];
	topic.posts.forEach((post, i) => {
		const at = postEpoch(topic, i);
		lines.push(
			'',
			`INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)`,
			`SELECT t.id, ${sql(post.author)}, ${sql(post.body)}, ${at}, 1, 1`,
			`FROM topics t WHERE t.board = ${sql(board)} AND t.slug = ${sql(topic.slug)}`,
			`  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = ${at});`
		);
	});
	return lines.join('\n');
}

/**
 * The idempotent seed SQL for one canon system's file area. Rows key on a
 * deterministic id (`canon:<board>:<NAME>`) so re-running inserts nothing.
 * Canon uploads are text-only (body inline, no R2 key); `size` is the UTF-8
 * byte count a real upload would have. `pinned_rank` lists them in module
 * order above community uploads, mirroring topics.
 */
export function canonFilesSql(system: CanonSystem): string {
	const statements: string[] = [
		`-- Canon file-area seed: ${system.name} (${system.id}).`,
		`-- GENERATED by src/lib/apps/dialer/content/seed.ts from the ${system.id} content`,
		`-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with`,
		`--   pnpm test:unit -- --update`,
		`-- Idempotent: files key on their deterministic canon id.`,
		''
	];
	system.files.forEach((file, rank) => {
		const id = `canon:${system.id}:${file.name}`;
		const size = new TextEncoder().encode(file.body).length;
		statements.push(
			`INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)`,
			`SELECT ${sql(id)}, ${sql(system.id)}, ${sql(file.name)}, ${sql(fileKind(file))}, ${size}, ${sql(file.uploader)}, ${sql(file.body)}, NULL, ${file.downloads}, ${canonDateEpoch(file.date)}, 1, ${rank}`,
			`WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = ${sql(id)});`,
			''
		);
	});
	return statements.join('\n');
}

/**
 * A post's timestamp: its authored date plus one minute per position in the
 * thread, so same-day replies keep their authored order in `ORDER BY
 * created_at` without inventing times the fiction never wrote down.
 */
function postEpoch(topic: CanonTopic, index: number): number {
	return canonDateEpoch(topic.posts[index].date) + index * 60;
}

/** A single-quoted SQL string literal. The only escape SQLite needs is ''. */
function sql(value: string): string {
	return `'${value.replaceAll("'", "''")}'`;
}
