import type { CanonSystem, CanonTopic } from './types';

/**
 * Canon → D1 seed generator. Turns a content module into an idempotent SQL
 * migration so canon and community posts share one store online (PRD: "canon
 * and community share one surface"). Topics key on (board, slug); posts key
 * on (topic, created_at) — re-running a seed inserts nothing. Seeded rows are
 * `canon=1 pinned=1` and immutable by construction: no API path updates or
 * deletes them.
 *
 * The generated file is a real migration (migrations/dialer/000N_canon_*.sql),
 * locked to this generator by a file-snapshot test in seed.test.ts — editing a
 * content module without regenerating fails CI. Canon FILE areas are not
 * seeded yet; that lands with the file routes (slice 3).
 */

/**
 * Epoch seconds for a canon date, `MM/DD/YY` or `MM/DD/YY HH:MM` (UTC). The
 * two-digit year lives in the 1900s — this universe never sees Y2K. Undated
 * hours land at noon so date-only posts stay unambiguous.
 */
export function canonDateEpoch(date: string): number {
	const match = /^(\d{2})\/(\d{2})\/(\d{2})(?: (\d{2}):(\d{2}))?$/.exec(date);
	if (!match) throw new Error(`canon date doesn't scan: "${date}"`);
	const [, mm, dd, yy, hh, min] = match;
	return (
		Date.UTC(
			1900 + Number(yy),
			Number(mm) - 1,
			Number(dd),
			Number(hh ?? '12'),
			Number(min ?? '0')
		) / 1000
	);
}

/** The complete, idempotent seed SQL for one canon system's message boards. */
export function canonSeedSql(system: CanonSystem): string {
	const statements: string[] = [
		`-- Canon content seed: ${system.name} (${system.id}).`,
		`-- GENERATED by src/lib/apps/dialer/content/seed.ts from the ${system.id} content`,
		`-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with`,
		`--   pnpm test:unit -- --update`,
		`-- Idempotent: topics key on (board, slug), posts on (topic, created_at).`,
		''
	];
	for (const section of system.sections) {
		for (const topic of section.topics) {
			statements.push(topicSql(system.id, section.slug, topic), '');
		}
	}
	return statements.join('\n');
}

function topicSql(board: string, section: string, topic: CanonTopic): string {
	const createdAt = postEpoch(topic, 0);
	const lines = [
		`INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned)`,
		`SELECT ${sql(board)}, ${sql(section)}, ${sql(topic.slug)}, ${sql(topic.title)}, ${sql(topic.posts[0].author)}, ${createdAt}, 1, 1`,
		`WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = ${sql(board)} AND slug = ${sql(topic.slug)});`
	];
	topic.posts.forEach((post, i) => {
		const at = postEpoch(topic, i);
		lines.push(
			'',
			`INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)`,
			`SELECT t.id, ${sql(post.author)}, ${sql(post.body)}, ${at}, 1, 1`,
			`FROM topics t WHERE t.board = ${sql(board)} AND t.slug = ${sql(topic.slug)}`,
			`  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = ${at});`
		);
	});
	return lines.join('\n');
}

/**
 * A post's timestamp: its authored date plus one minute per position in the
 * thread, so same-day replies keep their authored order in `ORDER BY
 * created_at` without inventing times the fiction never wrote down.
 */
function postEpoch(topic: CanonTopic, index: number): number {
	return canonDateEpoch(topic.posts[index].date) + index * 60;
}

/** A single-quoted SQL string literal. The only escape SQLite needs is ''. */
function sql(value: string): string {
	return `'${value.replaceAll("'", "''")}'`;
}
