-- Canon content seed: The Rusty Diskette (rusty-diskette).
-- GENERATED by src/lib/apps/dialer/content/seed.ts from the rusty-diskette content
-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with
--   pnpm test:unit -- --update
-- Idempotent: topics key on (board, slug), posts on (topic, created_at).

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned)
SELECT 'rusty-diskette', 'general', 'halloween-87', 'HALLOWEEN PLANS?', 'CAPT.VECTOR', 560779200, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'rusty-diskette' AND slug = 'halloween-87');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'CAPT.VECTOR', 'Two weeks out. The garage is getting the full treatment this year:
fog machine (borrowed), skeleton (paper), and the monitor graveyard
gets dragged onto the lawn. Six dead CRTs with candles inside.

The wife says it''s a fire hazard. I say it''s ATMOSPHERE.

Post your plans. Best costume idea gets 30 extra minutes of
board time. Judge''s decision (mine) is final.

-- CV', 560779200, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'halloween-87'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560779200);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 'going as a lineman. hard hat, tool belt, butt set on the hip.
nobody at the party will get it. that''s the point.', 560865660, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'halloween-87'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560865660);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'CAPT.VECTOR', 'Phracture wins already and he doesn''t even know what a costume
party is for. The 30 minutes are yours. Spend them wisely,
which for you means 3 AM. -- CV', 560865720, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'halloween-87'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560865720);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned)
SELECT 'rusty-diskette', 'general', 'amiga-vs-st', 'AMIGA VS ST (ROUND 40)', 'CAPT.VECTOR', 559828800, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'rusty-diskette' AND slug = 'amiga-vs-st');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'CAPT.VECTOR', 'I am REOPENING this topic because SOMEBODY (you know who you are)
filled up the last one arguing about custom chips until my poor
drive begged for mercy.

House rules this time:
1. No calling anyone''s computer a "toy."
2. Numbers or it didn''t happen.
3. When in doubt, remember my C64 in the corner is
   quietly beating you both on games per dollar.

-- CV', 559828800, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'amiga-vs-st'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 559828800);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', 'the ST has MIDI ports on the back. standard. from the factory.
that is the whole post.', 560001660, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'amiga-vs-st'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560001660);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 'and the amiga has a blitter that makes the ST look like it''s
drawing with a crayon held in its teeth. numbers: 4096 colors
vs 512. it didn''t happen, per rule 2.', 560088120, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'amiga-vs-st'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560088120);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned)
SELECT 'rusty-diskette', 'general', 'back-room-joke', 'WHAT DOES CV KEEP IN THE BACK?', 'NO.CARRIER', 560174400, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'rusty-diskette' AND slug = 'back-room-joke');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', 'heard from a guy that CV keeps the good stuff in a members-only
area. best ANSI in the 616, secret files, the works. true?', 560174400, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'back-room-joke'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560174400);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'CAPT.VECTOR', 'A gentleman never tells. But if you''re curious, come find me at
the main menu and ask me about the WEATHER. We get some
interesting weather out here by the garage.

-- CV', 560260860, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'back-room-joke'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560260860);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned)
SELECT 'rusty-diskette', 'trade', 'wtb-1541', 'WTB: WORKING 1541', 'PHRACTURE', 560347200, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'rusty-diskette' AND slug = 'wtb-1541');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 'wanted: one working 1541 drive. will trade two joysticks and a
slightly haunted C64. it types by itself sometimes. mostly the
letter J. otherwise a solid machine.', 560347200, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'wtb-1541'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560347200);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'CAPT.VECTOR', 'Define "sometimes." I have a 1541 that reads every third disk
and a healthy respect for ghosts. This could be the worst trade
in board history and I am LISTENING. -- CV', 560347260, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'wtb-1541'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560347260);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned)
SELECT 'rusty-diskette', 'trade', 'hayes-clone', 'FS: HAYES-COMPATIBLE 1200, $60', 'NO.CARRIER', 560606400, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'rusty-diskette' AND slug = 'hayes-clone');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', 'selling my old 1200 baud external. real hayes command set, not
the "mostly compatible" kind that hangs up when you sneeze.
$60 or best offer. upgrading to 2400 like a civilized person.', 560606400, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'hayes-clone'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560606400);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned)
SELECT 'rusty-diskette', 'grapevine', 'night-circuit', 'WHERE THE NIGHT PEOPLE WENT', 'PHRACTURE', 560433600, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'rusty-diskette' AND slug = 'night-circuit');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 'you didn''t hear this from me but the real late-night action moved
to {*C}NIGHT CIRCUIT{/}. mary runs a tight board. no games, no chatter,
just people who know things trading them after dark.

she only answers after 9 PM her time. {*W}555-8008{/}. tell her the
captain still owes her a crystal. she''ll know what it means.', 560433600, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'night-circuit'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560433600);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'CAPT.VECTOR', 'For the record: it was ONE crystal, it was a 4.433 MHz, and I
mailed it back in a padded envelope like a gentleman.

Mary if you''re reading this, the envelope was padded.

-- CV', 560520060, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'night-circuit'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560520060);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned)
SELECT 'rusty-diskette', 'grapevine', 'exchange-rumor', 'WEIRD NUMBERS IN THE EXCHANGE', 'NO.CARRIER', 560692800, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'rusty-diskette' AND slug = 'exchange-rumor');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', 'guy at the surplus store swears there are carriers in the 555
exchange that don''t belong to any board. no banner, no name,
just a login. probably nothing. probably test lines.

probably.', 560692800, 1, 1
FROM topics t WHERE t.board = 'rusty-diskette' AND t.slug = 'exchange-rumor'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560692800);
