-- Canon content seed: Night Circuit (night-circuit).
-- GENERATED by src/lib/apps/dialer/content/seed.ts from the night-circuit content
-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with
--   pnpm test:unit -- --update
-- Idempotent: topics key on (board, slug), posts on (topic, created_at).

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'night-circuit', 'late-shift', 'who-else-is-up', 'WHO ELSE IS UP RIGHT NOW', 'NO.CARRIER', 560144460, 1, 1, 0
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'night-circuit' AND slug = 'who-else-is-up');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', '3:41 AM. the house is asleep, the modem fan is the loudest thing
in the county, and the coffee stopped working around one.

roll call. what are you working on and why isn''t it done.', 560144460, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'who-else-is-up'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560144460);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 're-capping a power supply for a guy who paid me in a box of
mixed EPROMs. some of them are even blank. living the dream.', 560145780, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'who-else-is-up'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560145780);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'MAINFRAME.MARY', 'Shift change is at five. You are all between the wrong shifts.

Working: trunk utilization report nobody will read.
Not done because: it is accurate.', 560146620, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'who-else-is-up'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560146620);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'night-circuit', 'late-shift', 'sweep-excerpt', 'FOUND SOMETHING IN THE EXCHANGE', 'NO.CARRIER', 560488320, 1, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'night-circuit' AND slug = 'sweep-excerpt');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', 'ran a block of the 555 exchange last week. mostly what you''d
expect. excerpt:

  {C}5550109 ... VOICE
  5550110 ... NO ANSWER
  5550111 ... BUSY
  5550112 ... VOICE (angry)
  5550113 ... CARRIER 300bps. no banner. LOGIN prompt.
              drops after 3 tries.
  5550114 ... NO ANSWER{/}

no banner. no name. answers around the clock. doesn''t match any
board list i have. anyone know this one?

full log is in the file area if you want the rest of the block.', 560488320, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'sweep-excerpt'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560488320);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'MAINFRAME.MARY', 'Leave it alone.', 560493900, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'sweep-excerpt'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560493900);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', 'that''s not a no.', 560574420, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'sweep-excerpt'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560574420);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'night-circuit', 'late-shift', 'coffee-thread', 'CORRECT COFFEE FOR 4 AM', 'PHRACTURE', 560748780, 1, 1, 2
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'night-circuit' AND slug = 'coffee-thread');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 'percolator. the wait is part of the dose. fight me.', 560748780, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'coffee-thread'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560748780);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'MAINFRAME.MARY', 'Vending machine on sublevel 2. Button B4. It has never once
been good and it has never once been off.

Consistency is a spec. Flavor is a preference.', 560751660, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'coffee-thread'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560751660);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'night-circuit', 'phreak-physics', 'why-2600', 'WHY THE OLD TONES WORKED', 'MAINFRAME.MARY', 559972680, 1, 1, 3
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'night-circuit' AND slug = 'why-2600');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'MAINFRAME.MARY', 'Because the network carried its own control signals in the same
band as your voice. In-band signaling. The switch listened to the
line, and the line was you.

That era is closing. The control channel is moving out of band,
where you can''t hum at it. Nothing I post here opens any doors;
the doors are being removed.

History, not instructions. Learn the difference before posting.', 559972680, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'why-2600'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 559972680);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 'mary writing three whole paragraphs. somebody check on the
central office, i think it''s lonely in there.', 559974660, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'why-2600'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 559974660);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'MAINFRAME.MARY', 'Four, counting this one.', 559975980, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'why-2600'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 559975980);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'night-circuit', 'phreak-physics', 'crossbar-sounds', 'WHAT A CROSSBAR SOUNDS LIKE', 'MAINFRAME.MARY', 560316420, 1, 1, 4
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'night-circuit' AND slug = 'crossbar-sounds');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'MAINFRAME.MARY', 'A room full of relays deciding things. Thousands of small metal
choices a second. You can stand in the middle of it and hear
every call in the building as clicks.

The new digital offices are silent. Progress is quieter and it
tells you less.', 560316420, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'crossbar-sounds'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560316420);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', 'this is the only board where the sysop posts poetry about
switchgear and nobody blinks. never change.', 560318160, 1, 1
FROM topics t WHERE t.board = 'night-circuit' AND t.slug = 'crossbar-sounds'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560318160);
