-- Canon content seed: The Foundry (foundry).
-- GENERATED by src/lib/apps/dialer/content/seed.ts from the foundry content
-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with
--   pnpm test:unit -- --update
-- Idempotent: topics key on (board, slug), posts on (topic, created_at).

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'foundry', 'the-floor', 'shift-report', 'THIRD SHIFT REPORT', 'SLAG', 560433600, 1, 1, 0
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'foundry' AND slug = 'shift-report');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'SLAG', 'POUR WENT LONG TONIGHT SO THE BOARD WAS DOWN TIL TWO
IF YOU CALLED AND GOT NO ANSWER THAT WAS WHY
THE MACHINES COME FIRST THE MODEM COMES SECOND
THIS IS THE CORRECT ORDER OF THINGS', 560433600, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'shift-report'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560433600);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 'a board with honest downtime reasons. every other sysop says
"line noise." slag says "i was busy pouring liquid metal."
no contest.', 560520060, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'shift-report'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560520060);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'SLAG', 'IT WAS IRON NOT METAL
IRON IS A SPECIFIC METAL
PRECISION MATTERS ON THIS BOARD', 560520120, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'shift-report'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560520120);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'foundry', 'the-floor', 'broken-mill', 'THE BRIDGEPORT IS MAKING A NOISE', 'WF-7', 560692800, 1, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'foundry' AND slug = 'broken-mill');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'WF-7', 'describe the noise. and don''t say "bad." bad is a diagnosis,
not a description. is it once per revolution or continuous?
does it change with load? spindle or table?

thirty years of listening to machines. they all tell you
what''s wrong if you stop guessing and listen.', 560692800, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'broken-mill'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560692800);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'SLAG', 'ONCE PER REV AND IT CHANGES WITH LOAD
SO SPINDLE BEARING
I ALREADY KNEW BUT I WANTED IT ON RECORD THAT WF-7 ASKS
THE RIGHT QUESTIONS
MOST PEOPLE JUST SAY REPLACE THE BEARING
HE SAYS WHICH BEARING AND WHY
THATS THE DIFFERENCE', 560692860, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'broken-mill'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560692860);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'foundry', 'demo-den', 'molten-pour', 'MOLTEN POUR II - PROGRESS', 'SLAG', 560260800, 1, 1, 2
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'foundry' AND slug = 'molten-pour');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'SLAG', 'SIXTY FRAMES A SECOND OR IT DOESNT SHIP
THE FIRST ONE MADE A SYSOP CRY AND THE SEQUEL WILL NOT
EMBARRASS IT

CURRENT STATE
  PLASMA - DONE
  SCROLLER - DONE
  THE POUR - NOT DONE
THE POUR IS THE WHOLE POINT SO NO RELEASE DATE

RELEASE NOTES GO IN THE FILE AREA WHEN ITS READY
CHECK MOLTEN2.NFO FOR THE CREDITS LIST', 560260800, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'molten-pour'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560260800);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'NO.CARRIER', 'saw molten pour I running at a copy party in the spring.
the room went quiet. no notes, just recording history here
before the sequel makes everyone forget the original.', 560347260, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'molten-pour'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560347260);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'foundry', 'demo-den', 'size-limits', '4K OR IT DOESNT COUNT', 'SLAG', 559656000, 1, 1, 3
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'foundry' AND slug = 'size-limits');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'SLAG', 'EVERYONE ARGUING ABOUT WHOSE DEMO IS BIGGER HAS IT BACKWARDS
ANYONE CAN BE IMPRESSIVE IN 64K
DO IT IN 4K AND THEN TALK
CONSTRAINTS ARE THE ART FORM
THE FURNACE ONLY FITS SO MUCH IRON AND THATS WHY POURING
IT RIGHT MEANS SOMETHING', 559656000, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'size-limits'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 559656000);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'PHRACTURE', 'slag out here running a philosophy seminar with the shift key
welded down. she''s right though. 4k is chess, 64k is checkers.', 559742460, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'size-limits'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 559742460);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'foundry', 'old-iron', 'ghost-site', 'SITES THEY NEVER TURNED OFF', 'WF-7', 560088000, 1, 1, 4
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'foundry' AND slug = 'ghost-site');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'WF-7', 'since this is the retired-iron board, a story from my DOE days.

seismic monitoring site up north. i was the field tech - drove
up twice a month, changed tapes, kept the array listening.
january ''83 the program got defunded and they pulled everyone
out in a week. nobody decommissioned anything. no shutdown
order ever came through, so we didn''t shut it down.

last i knew the maintenance account still worked - OPERATOR,
password CROSSTALK. the dial-in was still listed in the site
binder. probably still ringing into an empty room.

four years now. i think about it every winter. all that
patience, still listening, and nobody left to read the tapes.', 560088000, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'ghost-site'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560088000);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'SLAG', 'THIS IS THE BEST POST EVER MADE ON THIS BOARD
A MACHINE THAT OUTLIVED ITS WHOLE DEPARTMENT
STILL DOING ITS JOB WITH NOBODY WATCHING
THATS NOT A GHOST STORY THATS A ROLE MODEL', 560174460, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'ghost-site'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560174460);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'WF-7', 'never thought of it that way. the binder''s long gone but i
remember the exchange was local. 555 like everything else
out here. never wrote the rest down and i''m not going to.
some doors you leave the way you found them.', 560260920, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'ghost-site'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 560260920);

INSERT INTO topics (board, section, slug, title, author, created_at, canon, pinned, pinned_rank)
SELECT 'foundry', 'old-iron', 'punch-cards', 'LAST TIME YOU TOUCHED A PUNCH CARD', 'WF-7', 559310400, 1, 1, 5
WHERE NOT EXISTS (SELECT 1 FROM topics WHERE board = 'foundry' AND slug = 'punch-cards');

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'WF-7', '1979, payroll system. dropped a tray of four hundred cards on
the stairwell landing and considered a career in agriculture.
they were numbered. i re-sorted them. it took two days and i
have never once complained about floppy disks since.', 559310400, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'punch-cards'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 559310400);

INSERT INTO posts (topic_id, author, body, created_at, canon, pinned)
SELECT t.id, 'SLAG', 'MY UNCLE KEPT A DECK IN HIS TOOLBOX FOR SHIMS
SAID IT WAS THE ONLY SOFTWARE HE EVER FOUND A USE FOR
HE WAS WRONG BUT IT WAS FUNNY', 559396860, 1, 1
FROM topics t WHERE t.board = 'foundry' AND t.slug = 'punch-cards'
  AND NOT EXISTS (SELECT 1 FROM posts p WHERE p.topic_id = t.id AND p.canon = 1 AND p.created_at = 559396860);
