-- Canon file-area seed: The Rusty Diskette (rusty-diskette).
-- GENERATED by src/lib/apps/dialer/content/seed.ts from the rusty-diskette content
-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with
--   pnpm test:unit -- --update
-- Idempotent: files key on their deterministic canon id.

INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)
SELECT 'canon:rusty-diskette:MODEM101.TXT', 'rusty-diskette', 'MODEM101.TXT', 'txt', 1003, 'CAPT.VECTOR', '                       MODEM 101 -- by Captain Vector
                    "Everything I know about not connecting"

1. BUY HAYES COMPATIBLE. Not "works with most software." Not "custom
   command set, very fast." HAYES. COMPATIBLE. You will thank me at
   2 AM when your terminal program actually hangs up the phone.

2. 8-N-1. Eight data bits, no parity, one stop bit. If a board wants
   7-E-1 it will say so, loudly, and it is probably run by a bank.

3. That screech when you connect is the two modems agreeing on how
   fast to talk. It is called a handshake. It is supposed to sound
   like that. Stop calling me about it.

4. If the line drops every time your mother picks up the kitchen
   extension, that is not line noise. That is your mother.

5. Turn the modem speaker ON. Yes it''s loud. It is also the only way
   to know whether you got a busy signal or a carrier before your
   software does. Information wants to be audible.

                                                        -- CV', NULL, 212, 555940800, 1, 0
WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = 'canon:rusty-diskette:MODEM101.TXT');

INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)
SELECT 'canon:rusty-diskette:ANSIDRAW.TXT', 'rusty-diskette', 'ANSIDRAW.TXT', 'txt', 752, 'CAPT.VECTOR', '                    SO YOU WANT TO DRAW ANSI SCREENS

The Rusty Diskette accepts ANSI art submissions for the login screen.
Rotating gallery, full credit, immortality (local).

RULES OF THE HOUSE:
- 80 columns. Count them. I will count them.
- 16 colors is plenty. If it was good enough for the IBM engineers
  who chose them apparently at random, it is good enough for you.
- No screens that "blink the whole time." One blink element per
  screen, like a tasteful earring.
- Sign your work. Handles only.

Submissions to the file area, name it YOURHANDLE.ANS. Current champ
is SLAG from over at The Foundry, whose "molten pour" screen made a
grown sysop tear up a little. The bar is high.

                                                        -- CV', NULL, 87, 557582400, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = 'canon:rusty-diskette:ANSIDRAW.TXT');

INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)
SELECT 'canon:rusty-diskette:FOUNDRY.TXT', 'rusty-diskette', 'FOUNDRY.TXT', 'txt', 996, 'SLAG', '##########################################################
#                                                        #
#   T H E   F O U N D R Y                                #
#                                                        #
#   THIRD SHIFT BBS FOR PEOPLE WHO MAKE THINGS           #
#                                                        #
#   SHOP TALK - DEMO DEN - OLD IRON                      #
#                                                        #
#   NO SUITS NO HOMEWORK NO SPEED LIMIT                  #
#                                                        #
#   CALL 555-4477                                        #
#                                                        #
#   SYSOP: SLAG                                          #
#   IF ITS 3AM AND THE POUR IS DONE SHES PROBABLY ON     #
#                                                        #
##########################################################

posted with permission of the management (me) -- CV', NULL, 149, 559137600, 1, 2
WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = 'canon:rusty-diskette:FOUNDRY.TXT');

-- Canon file-area seed: Night Circuit (night-circuit).
-- GENERATED by src/lib/apps/dialer/content/seed.ts from the night-circuit content
-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with
--   pnpm test:unit -- --update
-- Idempotent: files key on their deterministic canon id.

INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)
SELECT 'canon:night-circuit:SCANLOG.TXT', 'night-circuit', 'SCANLOG.TXT', 'txt', 1979, 'NO.CARRIER', 'EXCHANGE SWEEP -- 555-01XX BLOCK -- COMPLETE LOG
started 02:10, finished 04:52. one call per number, 20 rings max.
posted as-is. draw your own conclusions.

  5550100 ... VOICE
  5550101 ... NO ANSWER
  5550102 ... BUSY
  5550103 ... VOICE
  5550104 ... NO ANSWER
  5550105 ... NO ANSWER
  5550106 ... VOICE (answering machine)
  5550107 ... BUSY
  5550108 ... NO ANSWER
  5550109 ... VOICE
  5550110 ... NO ANSWER
  5550111 ... BUSY
  5550112 ... VOICE (angry)
  5550113 ... CARRIER 300bps. no banner. LOGIN prompt.
              drops after 3 tries. see below.
  5550114 ... NO ANSWER
  5550115 ... VOICE
  5550116 ... NO ANSWER
  5550117 ... VOICE (fax?)
  5550118 ... NO ANSWER
  5550119 ... BUSY
  5550120 ... VOICE
  5550121 ... NO ANSWER
  5550122 ... NO ANSWER
  5550123 ... VOICE (kid answered)
  5550124 ... BUSY
  5550125 ... NO ANSWER
  5550126 ... VOICE
  5550127 ... NO ANSWER
  5550128 ... NO ANSWER
  5550129 ... VOICE
  5550130 ... NO ANSWER
  5550131 ... BUSY
  5550132 ... NO ANSWER
  5550133 ... VOICE
  5550134 ... NO ANSWER
  5550135 ... NO ANSWER
  5550136 ... VOICE
  5550137 ... BUSY
  5550138 ... NO ANSWER
  5550139 ... VOICE (answering machine)
  5550140 ... NO ANSWER
  5550141 ... NO ANSWER
  5550142 ... VOICE
  5550143 ... NO ANSWER
  5550144 ... BUSY
  5550145 ... VOICE
  5550146 ... NO ANSWER
  5550147 ... NO ANSWER
  5550148 ... VOICE
  5550149 ... NO ANSWER

(second fifty ran the next night, log got eaten by a disk error.
nothing in it but voice and no answer. trust me or run it yourself.)

NOTES ON 0113:
- answers around the clock. every attempt, first ring.
- 300 baud only. tried 1200, it won''t train.
- no banner, no ident, straight to LOGIN.
- three strikes and it drops carrier. no lockout that i can
  tell -- redial and it answers again like nothing happened.
- not in any board list, not in the phone book, not in the
  cross-reference directory at the library. i checked.

somebody is paying the phone bill on that line. -- n.c', NULL, 61, 560520000, 1, 0
WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = 'canon:night-circuit:SCANLOG.TXT');

INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)
SELECT 'canon:night-circuit:MARY.FAQ', 'night-circuit', 'MARY.FAQ', 'txt', 986, 'MAINFRAME.MARY', 'FREQUENTLY ASKED QUESTIONS -- MAINFRAME MARY
compiled so I can stop answering them individually.

Q: Where do you work?
A: Nights.

Q: Are you really posting from inside a central office?
A: The timestamps are accurate.

Q: What''s your real name?
A: MAINFRAME.MARY is eight characters and a period. It fits in
   every field that matters.

Q: Why 3 to 5 AM only?
A: Traffic is lowest then. I like a quiet trunk.

Q: Is it true you built this board on switch hardware?
A: The board runs on what the board runs on.

Q: What do you know about the numbers in the exchange that
   answer with no banner?
A: More than I post.

Q: Will you tell us?
A: See previous answer.

Q: Are you a phone company employee?
A: The phone company has many employees.

Q: Somebody said you and Captain Vector used to run a board
   together in ''84. True?
A: He still owes me a crystal.

END OF FILE. Further questions will be added here, which is a
polite way of saying they will not be answered there either.', NULL, 118, 558446400, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = 'canon:night-circuit:MARY.FAQ');

-- Canon file-area seed: The Foundry (foundry).
-- GENERATED by src/lib/apps/dialer/content/seed.ts from the foundry content
-- module -- do not edit by hand. Locked by content/seed.test.ts; regenerate with
--   pnpm test:unit -- --update
-- Idempotent: files key on their deterministic canon id.

INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)
SELECT 'canon:foundry:MOLTEN2.NFO', 'foundry', 'MOLTEN2.NFO', 'txt', 828, 'SLAG', '      ___________________________________________________
     |                                                   |
     |   M O L T E N   P O U R   I I                     |
     |   A FOUNDRY PRODUCTION                            |
     |___________________________________________________|

STATUS ........ IN PROGRESS
TARGET ........ 60 FPS ON STOCK HARDWARE
RELEASE ....... WHEN THE POUR IS RIGHT

CREDITS
  CODE ........ SLAG
  MUSIC ....... TBD SEND TAPES
  ANSI ........ SLAG
  MORAL SUPPORT ... THE ENTIRE THIRD SHIFT

GREETINGS
  CAPT.VECTOR ... FIX YOUR 1541
  MAINFRAME.MARY ... THE QUIET ONES BUILD THE BEST BOARDS
  WF-7 ... TELL THE GHOST SITE STORY TO EVERYONE YOU MEET
           ITS IN OLD IRON IF YOU HAVENT READ IT
           GO READ IT ITS BETTER THAN THIS DEMO

NO RELEASE DATE
ASKING MOVES IT BACK A WEEK', NULL, 74, 560260800, 1, 0
WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = 'canon:foundry:MOLTEN2.NFO');

INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)
SELECT 'canon:foundry:POUR1.NFO', 'foundry', 'POUR1.NFO', 'txt', 574, 'SLAG', '      ___________________________________________________
     |                                                   |
     |   M O L T E N   P O U R                           |
     |   A FOUNDRY PRODUCTION                            |
     |___________________________________________________|

THE ONE THAT MADE A SYSOP CRY
HE KNOWS WHO HE IS
HE SIGNS EVERYTHING SO YOU PROBABLY DO TOO

RUNS ON ANYTHING WITH A HEARTBEAT
SIXTY FRAMES LOCKED
THE POUR SCENE IS HAND TIMED TO THE MUSIC
NO TRICKS NO PRECALC EVERYTHING LIVE

IF IT FLICKERS ON YOUR MACHINE YOUR MACHINE IS WRONG', NULL, 203, 545140800, 1, 1
WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = 'canon:foundry:POUR1.NFO');

INSERT INTO files (id, board, name, kind, size, uploader, body_text, r2_key, downloads, created_at, canon, pinned_rank)
SELECT 'canon:foundry:SHOPRULE.TXT', 'foundry', 'SHOPRULE.TXT', 'txt', 344, 'SLAG', 'RULES OF THE FLOOR
POSTED HERE BECAUSE I AM NOT TYPING THEM AGAIN

1 MEASURE TWICE
2 DEBURR YOUR EDGES - APPLIES TO PARTS AND TO POSTS
3 IF YOU BORROW A TOOL PUT IT BACK
4 IF YOU BREAK A TOOL SAY SO
5 NOBODY EVER GOT HURT BY ASKING A QUESTION
6 NOBODY EVER STAYED UNHURT BY PRETENDING THEY KNEW

THATS ALL OF THEM
SIX IS ENOUGH IF YOU MEAN THEM', NULL, 58, 552052800, 1, 2
WHERE NOT EXISTS (SELECT 1 FROM files WHERE id = 'canon:foundry:SHOPRULE.TXT');
